denoland/doc_website

frontend/src/components/JSDoc.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/SinglePage.tsx

Also fixed typealias links for singlepage

Added better table support to JSDoc

---

frontend/src/App.tsx
frontend/src/components/Breadcrumbs.tsx
frontend/src/components/Class.tsx
frontend/src/components/Function.tsx
frontend/src/components/Link.tsx
frontend/src/components/NotFound.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/SinglePage.tsx
frontend/src/routes/class.tsx
frontend/src/routes/enum.tsx
frontend/src/routes/function.tsx
frontend/src/routes/interface.tsx
frontend/src/routes/namespace.tsx
frontend/src/routes/typealias.tsx
frontend/src/routes/variable.tsx
frontend/src/util/prefix.ts

- Switched single and multi page links
- Added 404 page

Refactored frontend things

---

frontend/src/components/Class.tsx
frontend/src/components/Enum.tsx
frontend/src/components/Function.tsx
frontend/src/components/Interface.tsx
frontend/src/components/Namespace.tsx
frontend/src/components/SinglePage.tsx
frontend/src/components/TypeAlias.tsx
frontend/src/components/Variable.tsx
frontend/src/util/docs.ts

Added more card types

---

frontend/src/components/Variable.tsx
frontend/src/util/docs.ts

Is special casing these the right thing to do here?

Special cased constant variable namespaces

---

api/docs.ts
api/lib.deno.d.ts
components/Documentation.tsx
components/Enum.tsx
components/Sidebar.tsx
components/SinglePage.tsx
components/TsType.tsx
components/Variable.tsx
now.json
pages/404.tsx
pages/deno@latest.tsx
pages/https/[...url].tsx
pages/index.tsx
util/data.ts
util/docs.ts

Added special casing for Deno runtime types

---

components/Class.tsx
components/Documentation.tsx
components/Interface.tsx
components/Page.tsx
components/Sidebar.tsx
components/SinglePage.tsx
components/TsType.tsx
components/Variable.tsx
util/data.ts
util/docs.ts

Now even scoped types are properly linked. This is a slight perf hit, but nothing major and it can be improved further by using a hashmap for type searching. I fixed some other perf issues, and we now are at 92/100 lighthouse perf score for lib.deno.d.ts (which is a huge file). 100/100 for /std/fs/copy.ts. Anything smaller than lib.deno.d.ts should load within 5 seconds on 3G.

Advanced typexref

---

components/Class.tsx
components/SinglePage.tsx
components/TsType.tsx
util/docs.ts

Added inherited class fields

---

README.md
components/Documentation.tsx

Fix hash scroll

---

.github/workflows/ci.yml
api/docs.ts
components/Class.tsx
components/Documentation.tsx
components/Function.tsx
components/Sidebar.tsx
components/SinglePage.tsx
components/TsType.tsx
next.config.js
package.json
pages/index.tsx
postcss.config.js
util/docs.ts
worker/index.js
yarn.lock

Support for 0.40.0 features

---

components/SinglePage.tsx

[src] link

---

components/SinglePage.tsx

Fixes the left align on mobile

Center text under loading indicator

---

pages/_document.tsx

Fixes scrolled to anchors being hidden under the header. Introduced by #80

Fix scroll anchors

---

components/Page.tsx

fix: sidebar height

---

util/docs.ts

Fixed nested namespaces

---

README.md

Hello and congratulations on the Deno 1.0 release 🎉 
I cleaned up the readme with the correct names and hyperlinks.

Update readme with correct names and links

---

pages/index.tsx

This increases Lighthouse SEO score from 94 to 100
Current score: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdoc.deno.land%2F#seo

Add padding py-1 for links

---

components/Page.tsx

Change cursor to pointer in menu icon when hovering for a better user experience.

Change cursor to pointer in menu icon

---

components/Class.tsx
components/Documentation.tsx
components/Enum.tsx
components/Footer.tsx
components/Header.tsx
components/Interface.tsx
components/JSDoc.tsx
components/SinglePage.tsx
components/Wrapper.tsx
pages/about.tsx
pages/index.tsx
tailwind.config.js

Made the dark mode slightly brighter, and added a border around nested subcards.

Update dark mode with user feedback

---

components/Class.tsx
components/TsType.tsx
util/docs.ts

feat: link to MDN for JS builtins

---

components/TsType.tsx
util/docs.ts
vercel.json
yarn.lock

You can now click on types that are defined in a different module.
Example: Click on `BufReader` in https://doc-website-ftb63pns8.vercel.app/https/deno.land/std/http/mod.ts#ServerRequest

feat: remote module linking

---

pages/about.tsx

fixing documentation typo

---

api/docs.ts
vercel.json

chore: increase timeout to 60 seconds

---

components/Namespace.tsx
components/Sidebar.tsx
components/SinglePage.tsx
components/Variable.tsx
components/Wrapper.tsx
next.config.js
postcss.config.js
util/docs.ts

fix: ordering of symbols in sidebar

---

.github/workflows/ci.yml
components/Footer.tsx
pages/builtin/[version].tsx

For https://github.com/denoland/deno/pull/9503

chore: default branch main

---

worker/index.js

fix cloudflare breaking their fetch implementation

---

package.json
yarn.lock

It somehow fixes the 500 complaining about circular object returned from `getInitialProps`
More info: https://discord.com/channels/684898665143206084/778060450670575656/825393836909264928

Upgrade `next` and `preact`.

---

package.json
yarn.lock

Reverting denoland/doc_website#169 because the site went down:
Will try to investigate and reland later this week.

Revert "Upgrade `next` and `preact`."

---

components/Function.tsx
next.config.js
package.json
yarn.lock

See https://github.com/denoland/doc_website/pull/171#issuecomment-810920568
If there's something wrong with the added/removed packages/whatever please let me know, but AFAIK the site is working fine.

Upgrade to Next.js 10

---

components/Function.tsx
next.config.js
package.json
yarn.lock

This reverts commit f9bb397b969717ac8a7f36e63785beac100af05b.

Revert "Upgrade to next.js 10 (#176)"

---

components/JSDoc.tsx
pages/_document.tsx
public/styles/hljs/atom-one-dark.min.css
public/styles/hljs/atom-one-light.min.css

https://user-images.githubusercontent.com/29819102/119097429-57da7d80-ba32-11eb-8e01-e83084c5f353.mp4
Closes #198 
Closes #147

feat: use atom-one-light styles for code blocks in light mode

---

README.md

Some stuff I had to figure out through trial and error trying to get this to run locally, figured it'd be good to document it here for any future contributors.

docs: add contributing docs

---

components/Interface.tsx
next-env.d.ts
package.json
postcss.config.js
tsconfig.json
yarn.lock

~~It seems Preact is behaving when trying to upgrade to Next.js 12, so this serves as an intermediate update.~~
Trying 12 with subsequent commits.
Resolve #222

Upgrade to Next.js 12
